# Generated by Django 4.2.7 on 2023-11-07 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avatar',
            name='description',
        ),
        migrations.AddField(
            model_name='avatar',
            name='image',
            field=models.ImageField(default=1, upload_to='images/avatar/'),
            preserve_default=False,
        ),
    ]
