# Generated by Django 4.2.7 on 2023-11-07 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gans', '0002_remove_avatar_description_avatar_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images/bg/')),
            ],
        ),
    ]
