# Generated by Django 4.2.7 on 2023-11-07 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gans', '0004_delete_background_rename_image_avatar_avatar_images_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Avatar',
            new_name='Avatarandbackground',
        ),
    ]
