# Generated by Django 4.2.7 on 2023-11-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gans', '0005_rename_avatar_avatarandbackground'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backgroundandavatarcombine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='images/combine/')),
            ],
        ),
    ]
