# Generated by Django 4.2.7 on 2023-11-07 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gans', '0006_backgroundandavatarcombine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backgroundandavatarcombine',
            old_name='avatar',
            new_name='backgroun_final',
        ),
    ]
