# Generated by Django 4.2.7 on 2023-11-07 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gans', '0007_rename_avatar_backgroundandavatarcombine_backgroun_final'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio_inputs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.CharField(max_length=10000)),
                ('language', models.CharField(max_length=100)),
                ('voice', models.CharField(max_length=100)),
            ],
        ),
    ]
