# Generated by Django 4.2.5 on 2023-11-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gans", "0008_audio_inputs"),
    ]

    operations = [
        migrations.CreateModel(
            name="Avatar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("avatar_images", models.ImageField(upload_to="images/avatar/")),
            ],
        ),
        migrations.CreateModel(
            name="Background",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("background_image", models.ImageField(upload_to="images/bg/")),
            ],
        ),
        migrations.DeleteModel(name="Avatarandbackground",),
    ]
