# Generated by Django 4.2.5 on 2023-11-08 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gans", "0010_avatar_image_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="avatar",
            name="image_name",
            field=models.CharField(
                blank=True, editable=False, max_length=255, null=True
            ),
        ),
    ]
