# Generated by Django 4.2.5 on 2023-11-08 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gans", "0012_alter_avatar_image_name"),
    ]

    operations = [
        migrations.RemoveField(model_name="background", name="name",),
        migrations.AddField(
            model_name="background",
            name="image_name",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
