# Generated by Django 4.2.5 on 2023-11-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gans", "0013_remove_background_name_background_image_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="backgroundandavatarcombine",
            name="image_name",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
