# Generated by Django 4.2.5 on 2023-11-08 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gans", "0014_backgroundandavatarcombine_image_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="audio_inputs",
            name="gender",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="audio_inputs",
            name="video_image",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="audio_inputs",
            name="language",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="audio_inputs",
            name="prompt",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="audio_inputs",
            name="voice",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
