# Generated by Django 4.2.5 on 2023-11-08 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gans", "0015_audio_inputs_gender_audio_inputs_video_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="onlyClick",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("click", models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
