# Generated by Django 4.2.5 on 2023-11-08 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gans", "0016_onlyclick"),
    ]

    operations = [
        migrations.RenameModel(old_name="Audio_inputs", new_name="Audio_input",),
    ]
